# Generated by Django 5.2.14 on 2026-08-19 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobapplication",
            name="interview_date",
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="location",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="salary_max",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="salary_min",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="source",
            field=models.CharField(
                blank=True,
                help_text="Where you found the job, e.g. LinkedIn, company website.",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="jobapplication",
            name="work_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("remote", "Remote"),
                    ("hybrid", "Hybrid"),
                    ("onsite", "On-site"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobapplication",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="job_applications",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interview_type",
                    models.CharField(
                        choices=[
                            ("phone", "Phone"),
                            ("video", "Video"),
                            ("onsite", "On-site"),
                            ("technical", "Technical"),
                            ("behavioral", "Behavioral"),
                            ("final", "Final"),
                            ("other", "Other"),
                        ],
                        default="video",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("meeting_link", models.URLField(blank=True)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interviews",
                        to="jobs.jobapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["scheduled_at"],
            },
        ),
        migrations.CreateModel(
            name="StatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(blank=True, max_length=20)),
                ("new_status", models.CharField(max_length=20)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="jobs.jobapplication",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
            },
        ),
    ]
